# GIFT Framework Metadata Configuration
# Configuration for automatic metadata generation and validation

metadata:
  generation:
    enabled: true
    frequency: "on_push"
    output_format: ["json", "yaml"]
    
  validation:
    check_required_fields: true
    validate_links: true
    check_consistency: true
    
  required_fields:
    module:
      - "id"
      - "name" 
      - "purpose"
      - "status"
      - "last_updated"
    document:
      - "title"
      - "type"
      - "status"
      - "description"
      
  auto_generation:
    module_metadata: true
    document_metadata: false  # Manual for now
    cross_references: true
    
  output_directories:
    metadata_reports: ".github/metadata-reports"
    module_metadata: "{module_path}/MODULE_METADATA.yml"
    project_metadata: ".github/PROJECT_METADATA.yml"
    
  templates:
    module_metadata: |
      module:
        id: "{module_id}"
        name: "{module_name}"
        purpose: "{module_purpose}"
        status: "complete"
        last_updated: "{date}"
        
      content:
        files: []
        has_readme: {has_readme}
        document_count: {doc_count}
        
      structure:
        submodules: []
        file_count: {file_count}
        
  validation_rules:
    module_naming:
      pattern: "^0[1-6]_[a-z_]+$"
      required: true
      
    document_structure:
      require_readme: true
      require_metadata: false  # Auto-generated
      
    consistency_checks:
      - "module_id_matches_directory"
      - "document_links_valid"
      - "metadata_format_valid"
      
  reporting:
    generate_summary: true
    include_statistics: true
    track_changes: true
    
  maintenance:
    cleanup_old_metadata: false
    backup_before_update: true
    version_metadata: true
