name: ðŸ§® Theoretical Physics Question
description: Ask questions about GIFT theoretical foundations, mathematical derivations, or physics concepts
title: "[THEORY] "
labels: ["theoretical", "physics", "question"]
body:
  - type: markdown
    attributes:
      value: |
        ## Theoretical Physics Question
        
        Ask questions about GIFT theoretical foundations, mathematical derivations, or related physics concepts.
        
        ### Guidelines
        - Be specific about the theoretical aspect you're asking about
        - Reference relevant sections from the GIFT papers if applicable
        - Include mathematical expressions using LaTeX notation
        - Mention your background level (student, researcher, enthusiast)
  
  - type: textarea
    id: question
    attributes:
      label: "Your Theoretical Question"
      description: "Describe your question about GIFT theory, mathematical derivations, or physics concepts"
      placeholder: "e.g., How does the Eâ‚ˆÃ—Eâ‚ˆ dimensional reduction preserve information content?"
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: "Context & Background"
      description: "Provide context about your question and your background level"
      placeholder: "e.g., I'm a graduate student in theoretical physics studying unified field theories..."
    validations:
      required: false
  
  - type: textarea
    id: references
    attributes:
      label: "Relevant References"
      description: "Cite specific sections from GIFT papers, textbooks, or other sources"
      placeholder: "e.g., GIFT preprint Section 1.2, or Weinberg QFT Vol 3..."
    validations:
      required: false
  
  - type: dropdown
    id: complexity
    attributes:
      label: "Question Complexity Level"
      description: "Help us provide appropriately detailed responses"
      options:
        - "Basic - High school/undergraduate level"
        - "Intermediate - Graduate level"
        - "Advanced - Research level"
        - "Expert - Specialized knowledge required"
    validations:
      required: true
  
  - type: checkboxes
    id: categories
    attributes:
      label: "Related Physics Areas"
      description: "Select all that apply to your question"
      options:
        - label: "Electromagnetic sector (QED, fine structure constant)"
          required: false
        - label: "Electroweak sector (Weinberg angle, Higgs mechanism)"
          required: false
        - label: "Strong sector (QCD, Î›_QCD, hadronic physics)"
          required: false
        - label: "Cosmological sector (Hubble constant, dark energy)"
          required: false
        - label: "Fermion sector (mass relations, mixing matrices)"
          required: false
        - label: "Unification (Eâ‚ˆÃ—Eâ‚ˆ reduction, geometric parameters)"
          required: false
        - label: "Mathematical foundations (Lie groups, differential geometry)"
          required: false
