name: üî¨ Research Collaboration
description: Propose research ideas, collaborations, or discuss experimental validation of GIFT predictions
title: "[RESEARCH] "
labels: ["research", "collaboration", "experimental"]
body:
  - type: markdown
    attributes:
      value: |
        ## Research Collaboration
        
        Propose research ideas, collaborations, or discuss experimental validation of GIFT predictions.
        
        ### Guidelines
        - Clearly describe your research proposal or collaboration idea
        - Specify your institutional affiliation and research background
        - Explain how your work relates to GIFT framework
        - Include relevant publications or preliminary results if available
  
  - type: textarea
    id: proposal
    attributes:
      label: "Research Proposal or Collaboration Idea"
      description: "Describe your research idea, experimental proposal, or collaboration opportunity"
      placeholder: "e.g., I propose to test GIFT predictions for the fine structure constant using precision spectroscopy..."
    validations:
      required: true
  
  - type: textarea
    id: background
    attributes:
      label: "Your Research Background"
      description: "Describe your research experience and institutional affiliation"
      placeholder: "e.g., I'm a postdoc in experimental particle physics at CERN, working on precision measurements..."
    validations:
      required: true
  
  - type: dropdown
    id: research_type
    attributes:
      label: "Type of Research"
      description: "What type of research are you proposing?"
      options:
        - "Theoretical development"
        - "Experimental validation"
        - "Computational modeling"
        - "Data analysis"
        - "Educational materials"
        - "Software development"
        - "Cross-disciplinary collaboration"
        - "Other"
    validations:
      required: true
  
  - type: checkboxes
    id: gift_aspects
    attributes:
      label: "GIFT Framework Aspects"
      description: "Which aspects of GIFT are relevant to your research?"
      options:
        - label: "Electromagnetic predictions (Œ±‚Åª¬π, g-factor corrections)"
          required: false
        - label: "Electroweak predictions (sin¬≤Œ∏_W, Higgs parameters)"
          required: false
        - label: "Strong sector predictions (Œ±_s, Œõ_QCD, f_œÄ)"
          required: false
        - label: "Cosmological predictions (H‚ÇÄ, dark energy, Hubble tension)"
          required: false
        - label: "Fermion mass relations (Koide, mixing matrices)"
          required: false
        - label: "E‚Çà√óE‚Çà dimensional reduction mechanisms"
          required: false
        - label: "Geometric parameter derivations"
          required: false
        - label: "Mathematical foundations (Lie groups, cohomology)"
          required: false
  
  - type: textarea
    id: timeline
    attributes:
      label: "Proposed Timeline"
      description: "What is your proposed timeline for this research?"
      placeholder: "e.g., 6-month theoretical study followed by 1-year experimental validation..."
    validations:
      required: false
  
  - type: textarea
    id: resources
    attributes:
      label: "Available Resources"
      description: "What resources, facilities, or expertise can you bring to this collaboration?"
      placeholder: "e.g., Access to precision spectroscopy lab, computational cluster, expertise in QFT..."
    validations:
      required: false
  
  - type: textarea
    id: publications
    attributes:
      label: "Relevant Publications"
      description: "Include links to relevant publications or preliminary results"
      placeholder: "e.g., https://arxiv.org/abs/... or preliminary data from our lab..."
    validations:
      required: false
  
  - type: dropdown
    id: commitment
    attributes:
      label: "Collaboration Commitment Level"
      description: "What level of collaboration are you seeking?"
      options:
        - "Informal discussion and idea exchange"
        - "Regular collaboration on specific project"
        - "Long-term research partnership"
        - "Co-authorship on publications"
        - "Joint funding applications"
        - "Other"
    validations:
      required: true
