name: 💬 General Discussion
description: General questions, ideas, or community discussions about GIFT framework
title: "[DISCUSSION] "
labels: ["general", "community", "discussion"]
body:
  - type: markdown
    attributes:
      value: |
        ## General Discussion
        
        General questions, ideas, or community discussions about GIFT framework.
        
        ### Guidelines
        - Be respectful and constructive in discussions
        - Stay on topic related to GIFT framework and theoretical physics
        - Use clear and concise language
        - Support your arguments with evidence or references when possible
  
  - type: textarea
    id: topic
    attributes:
      label: "Discussion Topic"
      description: "What would you like to discuss about GIFT framework?"
      placeholder: "e.g., I'd like to discuss the implications of GIFT predictions for future experiments..."
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: "Discussion Category"
      description: "What type of discussion is this?"
      options:
        - "Question about GIFT predictions"
        - "Ideas for framework improvements"
        - "Community feedback and suggestions"
        - "Educational discussion"
        - "Philosophical implications"
        - "Comparison with other theories"
        - "Future directions"
        - "Other"
    validations:
      required: true
  
  - type: textarea
    id: details
    attributes:
      label: "Detailed Description"
      description: "Provide more details about your discussion topic"
      placeholder: "Elaborate on your topic, provide context, and explain what specific aspects you'd like to discuss..."
    validations:
      required: true
  
  - type: checkboxes
    id: interests
    attributes:
      label: "Areas of Interest"
      description: "Select areas that interest you for this discussion"
      options:
        - label: "Theoretical foundations and mathematical derivations"
          required: false
        - label: "Experimental predictions and validation"
          required: false
        - label: "Computational tools and implementation"
          required: false
        - label: "Educational applications and outreach"
          required: false
        - label: "Philosophical implications of geometric unification"
          required: false
        - label: "Comparison with Standard Model and other theories"
          required: false
        - label: "Future research directions"
          required: false
        - label: "Community building and collaboration"
          required: false
  
  - type: textarea
    id: context
    attributes:
      label: "Your Background & Perspective"
      description: "Help others understand your perspective and background"
      placeholder: "e.g., I'm a physics enthusiast interested in unified theories, or I'm a researcher in cosmology..."
    validations:
      required: false
  
  - type: dropdown
    id: audience
    attributes:
      label: "Target Audience"
      description: "Who would you like to engage in this discussion?"
      options:
        - "Anyone interested in GIFT"
        - "Theoretical physicists"
        - "Experimental physicists"
        - "Students and educators"
        - "Computational physicists"
        - "Science communicators"
        - "Open source contributors"
        - "All community members"
    validations:
      required: true
