name: 🐛 Bug Report
description: Report bugs or issues with GIFT framework code, calculations, or documentation
title: "[BUG] "
labels: ["bug", "issue"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Report bugs or issues with GIFT framework code, calculations, or documentation.
        
        ### Guidelines
        - Check existing issues before creating a new one
        - Provide detailed steps to reproduce the bug
        - Include error messages and expected vs actual behavior
        - Specify your environment details
  
  - type: textarea
    id: summary
    attributes:
      label: "Bug Summary"
      description: "Brief summary of the bug"
      placeholder: "e.g., Hubble constant calculation returns incorrect value..."
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: "Detailed Description"
      description: "Describe the bug in detail"
      placeholder: "Provide a detailed description of what went wrong..."
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the bug"
      placeholder: |
        1. Import the cosmological sector module
        2. Create HubbleCalculator instance
        3. Call calculate_hubble_constant()
        4. Compare with expected value
    validations:
      required: true
  
  - type: textarea
    id: code
    attributes:
      label: "Code to Reproduce"
      description: "Include code that reproduces the bug"
      render: python
      placeholder: |
        ```python
        from sectors.cosmological import HubbleCalculator
        calc = HubbleCalculator()
        result = calc.calculate_hubble_constant()
        print(f"Result: {result}")
        ```
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "Expected: H₀ = 72.93 km/s/Mpc"
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Actual: H₀ = 67.36 km/s/Mpc (incorrect value)"
    validations:
      required: true
  
  - type: textarea
    id: error
    attributes:
      label: "Error Messages"
      description: "Include any error messages or tracebacks"
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File "test.py", line 3, in <module>
        ValueError: Invalid parameter value
    validations:
      required: false
  
  - type: dropdown
    id: component
    attributes:
      label: "Affected Component"
      description: "Which part of GIFT is affected?"
      options:
        - "Core GIFT framework"
        - "Electromagnetic sector"
        - "Cosmological sector"
        - "Unification sector"
        - "Electroweak sector"
        - "Strong sector"
        - "Fermion sector"
        - "GIFT Translator"
        - "Documentation"
        - "Examples"
        - "Other"
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: "Bug Severity"
      description: "How severe is this bug?"
      options:
        - "Critical - Framework completely broken"
        - "High - Major functionality affected"
        - "Medium - Some calculations incorrect"
        - "Low - Minor issue or cosmetic problem"
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: "Environment Details"
      description: "Your system environment"
      placeholder: |
        - Python version: 3.9.7
        - Operating System: Windows 10
        - GIFT version: 1.0.0
        - Dependencies: numpy 1.21.0, etc.
    validations:
      required: true
