name: Experimental Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *' # Daily at 4 AM UTC

env:
  PYTHON_VERSION: '3.11'

jobs:
  validate-experiments:
    name: Validate Experimental Predictions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml numpy matplotlib
        
    - name: Run Experimental Validation Tests
      run: |
        echo "Running experimental validation tests..."
        python tests/test_experimental_validation.py
        
    - name: Upload Experimental Validation Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: experimental-validation-reports
        path: github-config/validation-reports/
        if-no-files-found: warn
        
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = 'github-config/validation-reports/validation-summary.md';
          if (fs.existsSync(reportPath)) {
            const report = fs.readFileSync(reportPath, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Experimental Validation Report\n\n${report}`
            });
          }


