name: Notebook Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM UTC

env:
  PYTHON_VERSION: '3.11'

jobs:
  test-notebooks:
    name: Test Jupyter Notebooks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert notebook ipykernel jupyter
        
    - name: Test Notebook Execution
      run: |
        echo "Testing notebook execution..."
        python tests/test_notebooks.py
        
    - name: Upload Notebook Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: notebook-test-reports
        path: github-config/test-reports/
        if-no-files-found: warn
        
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = 'github-config/test-reports/test_summary.md';
          if (fs.existsSync(reportPath)) {
            const report = fs.readFileSync(reportPath, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Notebook Test Report\n\n${report}`
            });
          }

