name: Coq CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'COQ/**'
      - '.github/workflows/coq.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'COQ/**'
      - '.github/workflows/coq.yml'
  workflow_dispatch:

env:
  COQ_VERSION: "8.18"

jobs:
  build:
    name: Build GIFT Coq Formalization
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: COQ

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init --disable-sandboxing -y
          eval $(opam env)
          opam pin add coq ${{ env.COQ_VERSION }}.0 -y
          echo "Coq installed:"
          opam exec -- coqc --version

      - name: Cache Opam
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-coq-${{ env.COQ_VERSION }}-${{ hashFiles('COQ/_CoqProject') }}
          restore-keys: |
            ${{ runner.os }}-opam-coq-${{ env.COQ_VERSION }}-
            ${{ runner.os }}-opam-coq-

      - name: Build dependencies
        run: |
          eval $(opam env)
          opam exec -- coqdep -Q . GIFT $(cat _CoqProject | grep '\.v$') > .depend || true

      - name: Build GIFT Coq
        run: |
          eval $(opam env)
          opam exec -- make -j2

      - name: Verify no Admitted statements
        run: |
          echo "Checking for 'Admitted' in Certificate modules..."
          if grep -r "Admitted\." Certificate/; then
            echo "ERROR: Found 'Admitted' in Certificate modules!"
            exit 1
          else
            echo "No Admitted found in Certificate modules"
          fi

      - name: Check for axioms (informational)
        run: |
          echo "=== Axiom Audit ==="
          echo "Checking for explicit axioms..."
          grep -r "^Axiom\|^Parameter" . --include="*.v" || echo "No explicit axioms found"
        continue-on-error: true

      - name: Build summary
        if: always()
        run: |
          eval $(opam env) || true
          echo "## GIFT Coq Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Item | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Coq Version | ${{ env.COQ_VERSION }} |" >> $GITHUB_STEP_SUMMARY
          MODULES=$(cat _CoqProject | grep '\.v$' | wc -l)
          echo "| Modules | $MODULES |" >> $GITHUB_STEP_SUMMARY
          if ls *.vo 2>/dev/null || ls */*.vo 2>/dev/null; then
            echo "| Build | Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Build | Failed |" >> $GITHUB_STEP_SUMMARY
          fi

  lint:
    name: Lint Coq code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: COQ

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for issues
        run: |
          echo "=== Coq Code Analysis ==="

          # Count lines of Coq code
          LINES=$(find . -name "*.v" -exec cat {} + | wc -l)
          echo "Total lines of Coq code: $LINES"

          # Count theorems
          THEOREMS=$(grep -r "^Theorem\|^Lemma" . --include="*.v" | wc -l)
          echo "Total theorems/lemmas: $THEOREMS"

          # Check for Admitted (incomplete proofs)
          ADMITTED=$(grep -r "Admitted\." . --include="*.v" | wc -l)
          echo "Admitted statements: $ADMITTED"

          # Check for explicit axioms
          AXIOMS=$(grep -r "^Axiom\|^Parameter" . --include="*.v" | wc -l)
          echo "Explicit axioms/parameters: $AXIOMS"

      - name: Lint summary
        if: always()
        run: |
          echo "## Coq Lint Summary" >> $GITHUB_STEP_SUMMARY
          LINES=$(find . -name "*.v" -exec cat {} + | wc -l)
          THEOREMS=$(grep -r "^Theorem\|^Lemma" . --include="*.v" | wc -l)
          ADMITTED=$(grep -r "Admitted\." . --include="*.v" | wc -l)
          echo "| Metric | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lines of code | $LINES |" >> $GITHUB_STEP_SUMMARY
          echo "| Theorems/Lemmas | $THEOREMS |" >> $GITHUB_STEP_SUMMARY
          echo "| Admitted | $ADMITTED |" >> $GITHUB_STEP_SUMMARY
