name: gift-framework
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - pip
  - pip:
    - zenodo-client 
