# GitHub Pages configuration for GIFT Translator
title: GIFT Translator - Matrix Style
description: Bidirectional translation between Standard Model and Geometric Information Field Theory
theme: minima

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom settings
repository: gift-framework/gift
github_username: gift-framework

# Build settings
markdown: kramdown
highlighter: rouge
