-"-"-"-
-U-n-i-t- -t-e-s-t-s- -f-o-r- -a-u-t-o-m-a-t-e-d- -a-g-e-n-t-s-.-
-
-T-e-s-t-s- -v-e-r-i-f-i-e-r-,- -u-n-i-c-o-d-e- -s-a-n-i-t-i-z-e-r-,- -d-o-c-s- -i-n-t-e-g-r-i-t-y-,- -a-n-d- -o-t-h-e-r- -a-g-e-n-t-s-.-
-"-"-"-
-
-i-m-p-o-r-t- -p-y-t-e-s-t-
-f-r-o-m- -p-a-t-h-l-i-b- -i-m-p-o-r-t- -P-a-t-h-
-i-m-p-o-r-t- -s-y-s-
-i-m-p-o-r-t- -t-e-m-p-f-i-l-e-
-i-m-p-o-r-t- -o-s-
-
-#- -A-d-d- -p-r-o-j-e-c-t- -r-o-o-t- -t-o- -p-a-t-h- -f-o-r- -i-m-p-o-r-t-s-
-p-r-o-j-e-c-t-_-r-o-o-t- -=- -P-a-t-h-(-_-_-f-i-l-e-_-_-)-.-p-a-r-e-n-t-.-p-a-r-e-n-t-.-p-a-r-e-n-t-
-s-y-s-.-p-a-t-h-.-i-n-s-e-r-t-(-0-,- -s-t-r-(-p-r-o-j-e-c-t-_-r-o-o-t-)-)-
-
-f-r-o-m- -a-s-s-e-t-s-.-a-g-e-n-t-s-.-b-a-s-e- -i-m-p-o-r-t- -A-g-e-n-t-R-e-s-u-l-t-
-f-r-o-m- -a-s-s-e-t-s-.-a-g-e-n-t-s-.-v-e-r-i-f-i-e-r- -i-m-p-o-r-t- -V-e-r-i-f-i-e-r-A-g-e-n-t-
-f-r-o-m- -a-s-s-e-t-s-.-a-g-e-n-t-s-.-d-o-c-s-_-i-n-t-e-g-r-i-t-y- -i-m-p-o-r-t- -D-o-c-s-I-n-t-e-g-r-i-t-y-A-g-e-n-t-
-f-r-o-m- -a-s-s-e-t-s-.-a-g-e-n-t-s-.-u-n-i-c-o-d-e-_-s-a-n-i-t-i-z-e-r- -i-m-p-o-r-t- -U-n-i-c-o-d-e-S-a-n-i-t-i-z-e-r-A-g-e-n-t-
-f-r-o-m- -a-s-s-e-t-s-.-a-g-e-n-t-s-.-u-t-i-l-s-.-m-a-r-k-d-o-w-n- -i-m-p-o-r-t- -p-a-r-s-e-_-l-i-n-k-s-,- -e-x-t-r-a-c-t-_-s-t-a-t-u-s-_-t-a-g-s-
-f-r-o-m- -a-s-s-e-t-s-.-a-g-e-n-t-s-.-u-t-i-l-s-.-f-s- -i-m-p-o-r-t- -d-i-s-c-o-v-e-r-_-f-i-l-e-s-
-
-
-c-l-a-s-s- -T-e-s-t-A-g-e-n-t-R-e-s-u-l-t-:-
- - - - -"-"-"-T-e-s-t- -A-g-e-n-t-R-e-s-u-l-t- -d-a-t-a- -s-t-r-u-c-t-u-r-e-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-a-g-e-n-t-_-r-e-s-u-l-t-_-c-r-e-a-t-i-o-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -c-r-e-a-t-i-n-g- -a-n- -A-g-e-n-t-R-e-s-u-l-t-.-"-"-"-
- - - - - - - - -r-e-s-u-l-t- -=- -A-g-e-n-t-R-e-s-u-l-t-(-
- - - - - - - - - - - - -n-a-m-e-=-"-t-e-s-t-"-,-
- - - - - - - - - - - - -o-k-=-T-r-u-e-,-
- - - - - - - - - - - - -i-s-s-u-e-s-=-[-]-,-
- - - - - - - - - - - - -s-u-m-m-a-r-y-=-"-A-l-l- -g-o-o-d-"-
- - - - - - - - -)-
-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-n-a-m-e- -=-=- -"-t-e-s-t-"-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-o-k- -i-s- -T-r-u-e-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-i-s-s-u-e-s- -=-=- -[-]-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-s-u-m-m-a-r-y- -=-=- -"-A-l-l- -g-o-o-d-"-
-
- - - - -d-e-f- -t-e-s-t-_-a-g-e-n-t-_-r-e-s-u-l-t-_-w-i-t-h-_-i-s-s-u-e-s-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -A-g-e-n-t-R-e-s-u-l-t- -w-i-t-h- -i-s-s-u-e-s-.-"-"-"-
- - - - - - - - -i-s-s-u-e-s- -=- -[-
- - - - - - - - - - - - -{-"-t-y-p-e-"-:- -"-e-r-r-o-r-"-,- -"-f-i-l-e-"-:- -"-t-e-s-t-.-m-d-"-,- -"-e-r-r-o-r-"-:- -"-b-r-o-k-e-n- -l-i-n-k-"-}-,-
- - - - - - - - - - - - -{-"-t-y-p-e-"-:- -"-w-a-r-n-i-n-g-"-,- -"-f-i-l-e-"-:- -"-d-o-c-.-m-d-"-,- -"-w-a-r-n-i-n-g-"-:- -"-m-i-s-s-i-n-g- -t-a-g-"-}-
- - - - - - - - -]-
-
- - - - - - - - -r-e-s-u-l-t- -=- -A-g-e-n-t-R-e-s-u-l-t-(-
- - - - - - - - - - - - -n-a-m-e-=-"-t-e-s-t-"-,-
- - - - - - - - - - - - -o-k-=-F-a-l-s-e-,-
- - - - - - - - - - - - -i-s-s-u-e-s-=-i-s-s-u-e-s-,-
- - - - - - - - - - - - -s-u-m-m-a-r-y-=-"-F-o-u-n-d- -2- -i-s-s-u-e-s-"-
- - - - - - - - -)-
-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-o-k- -i-s- -F-a-l-s-e-
- - - - - - - - -a-s-s-e-r-t- -l-e-n-(-r-e-s-u-l-t-.-i-s-s-u-e-s-)- -=-=- -2-
-
-
-c-l-a-s-s- -T-e-s-t-M-a-r-k-d-o-w-n-U-t-i-l-s-:-
- - - - -"-"-"-T-e-s-t- -m-a-r-k-d-o-w-n- -u-t-i-l-i-t-y- -f-u-n-c-t-i-o-n-s-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-p-a-r-s-e-_-l-i-n-k-s-_-s-i-m-p-l-e-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -p-a-r-s-i-n-g- -s-i-m-p-l-e- -m-a-r-k-d-o-w-n- -l-i-n-k-s-.-"-"-"-
- - - - - - - - -t-e-x-t- -=- -"-[-E-x-a-m-p-l-e-]-(-h-t-t-p-s-:-/-/-e-x-a-m-p-l-e-.-c-o-m-)-"-
- - - - - - - - -l-i-n-k-s- -=- -l-i-s-t-(-p-a-r-s-e-_-l-i-n-k-s-(-t-e-x-t-)-)-
-
- - - - - - - - -a-s-s-e-r-t- -l-e-n-(-l-i-n-k-s-)- -=-=- -1-
- - - - - - - - -a-s-s-e-r-t- -l-i-n-k-s-[-0-]-[-0-]- -=-=- -"-E-x-a-m-p-l-e-"-
- - - - - - - - -a-s-s-e-r-t- -l-i-n-k-s-[-0-]-[-1-]- -=-=- -"-h-t-t-p-s-:-/-/-e-x-a-m-p-l-e-.-c-o-m-"-
-
- - - - -d-e-f- -t-e-s-t-_-p-a-r-s-e-_-l-i-n-k-s-_-m-u-l-t-i-p-l-e-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -p-a-r-s-i-n-g- -m-u-l-t-i-p-l-e- -l-i-n-k-s-.-"-"-"-
- - - - - - - - -t-e-x-t- -=- -"-[-L-i-n-k-1-]-(-u-r-l-1-)- -s-o-m-e- -t-e-x-t- -[-L-i-n-k-2-]-(-u-r-l-2-)-"-
- - - - - - - - -l-i-n-k-s- -=- -l-i-s-t-(-p-a-r-s-e-_-l-i-n-k-s-(-t-e-x-t-)-)-
-
- - - - - - - - -a-s-s-e-r-t- -l-e-n-(-l-i-n-k-s-)- -=-=- -2-
- - - - - - - - -a-s-s-e-r-t- -l-i-n-k-s-[-0-]-[-1-]- -=-=- -"-u-r-l-1-"-
- - - - - - - - -a-s-s-e-r-t- -l-i-n-k-s-[-1-]-[-1-]- -=-=- -"-u-r-l-2-"-
-
- - - - -d-e-f- -t-e-s-t-_-p-a-r-s-e-_-l-i-n-k-s-_-r-e-l-a-t-i-v-e-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -p-a-r-s-i-n-g- -r-e-l-a-t-i-v-e- -l-i-n-k-s-.-"-"-"-
- - - - - - - - -t-e-x-t- -=- -"-[-D-o-c-]-(-.-.-/-d-o-c-s-/-f-i-l-e-.-m-d-)-"-
- - - - - - - - -l-i-n-k-s- -=- -l-i-s-t-(-p-a-r-s-e-_-l-i-n-k-s-(-t-e-x-t-)-)-
-
- - - - - - - - -a-s-s-e-r-t- -l-e-n-(-l-i-n-k-s-)- -=-=- -1-
- - - - - - - - -a-s-s-e-r-t- -l-i-n-k-s-[-0-]-[-1-]- -=-=- -"-.-.-/-d-o-c-s-/-f-i-l-e-.-m-d-"-
-
- - - - -d-e-f- -t-e-s-t-_-e-x-t-r-a-c-t-_-s-t-a-t-u-s-_-t-a-g-s-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -e-x-t-r-a-c-t-i-n-g- -s-t-a-t-u-s- -t-a-g-s-.-"-"-"-
- - - - - - - - -t-e-x-t- -=- -"-"-"-
- - - - - - - - -S-o-m-e- -t-e-x-t- -h-e-r-e-.-
- - - - - - - - -S-t-a-t-u-s-:- -*-*-P-R-O-V-E-N-*-*-
- - - - - - - - -M-o-r-e- -t-e-x-t-.-
- - - - - - - - -S-t-a-t-u-s-:- -*-*-D-E-R-I-V-E-D-*-*-
- - - - - - - - -E-v-e-n- -m-o-r-e-.-
- - - - - - - - -"-"-"-
-
- - - - - - - - -t-a-g-s- -=- -s-e-t-(-e-x-t-r-a-c-t-_-s-t-a-t-u-s-_-t-a-g-s-(-t-e-x-t-)-)-
-
- - - - - - - - -a-s-s-e-r-t- -"-P-R-O-V-E-N-"- -i-n- -t-a-g-s-
- - - - - - - - -a-s-s-e-r-t- -"-D-E-R-I-V-E-D-"- -i-n- -t-a-g-s-
-
- - - - -d-e-f- -t-e-s-t-_-e-x-t-r-a-c-t-_-s-t-a-t-u-s-_-t-a-g-s-_-v-a-r-i-o-u-s-_-f-o-r-m-a-t-s-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -s-t-a-t-u-s- -t-a-g-s- -i-n- -v-a-r-i-o-u-s- -f-o-r-m-a-t-s-.-"-"-"-
- - - - - - - - -t-e-x-t- -=- -"-"-"-
- - - - - - - - -*-*-P-R-O-V-E-N-*-*-:- -e-x-a-c-t- -r-e-s-u-l-t-
- - - - - - - - -S-t-a-t-u-s-:- -T-O-P-O-L-O-G-I-C-A-L-
- - - - - - - - -(-T-H-E-O-R-E-T-I-C-A-L-)-
- - - - - - - - -"-"-"-
-
- - - - - - - - -t-a-g-s- -=- -s-e-t-(-e-x-t-r-a-c-t-_-s-t-a-t-u-s-_-t-a-g-s-(-t-e-x-t-)-)-
-
- - - - - - - - -#- -S-h-o-u-l-d- -e-x-t-r-a-c-t- -t-a-g-s- -i-n- -v-a-r-i-o-u-s- -f-o-r-m-a-t-s-
- - - - - - - - -a-s-s-e-r-t- -l-e-n-(-t-a-g-s-)- ->-=- -1-
-
-
-c-l-a-s-s- -T-e-s-t-F-i-l-e-S-y-s-t-e-m-U-t-i-l-s-:-
- - - - -"-"-"-T-e-s-t- -f-i-l-e- -s-y-s-t-e-m- -u-t-i-l-i-t-y- -f-u-n-c-t-i-o-n-s-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-d-i-s-c-o-v-e-r-_-f-i-l-e-s-_-p-a-t-t-e-r-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -f-i-l-e- -d-i-s-c-o-v-e-r-y- -w-i-t-h- -p-a-t-t-e-r-n-s-.-"-"-"-
- - - - - - - - -r-o-o-t- -=- -P-a-t-h-(-_-_-f-i-l-e-_-_-)-.-p-a-r-e-n-t-.-p-a-r-e-n-t-.-p-a-r-e-n-t-
- - - - - - - - -p-a-t-t-e-r-n-s- -=- -[-"-R-E-A-D-M-E-.-m-d-"-,- -"-*-.-p-y-"-]-
-
- - - - - - - - -f-i-l-e-s- -=- -d-i-s-c-o-v-e-r-_-f-i-l-e-s-(-r-o-o-t-,- -p-a-t-t-e-r-n-s-)-
-
- - - - - - - - -#- -S-h-o-u-l-d- -f-i-n-d- -a-t- -l-e-a-s-t- -R-E-A-D-M-E-.-m-d-
- - - - - - - - -r-e-a-d-m-e-_-f-o-u-n-d- -=- -a-n-y-(-f-.-n-a-m-e- -=-=- -"-R-E-A-D-M-E-.-m-d-"- -f-o-r- -f- -i-n- -f-i-l-e-s-)-
- - - - - - - - -a-s-s-e-r-t- -r-e-a-d-m-e-_-f-o-u-n-d-
-
- - - - -d-e-f- -t-e-s-t-_-d-i-s-c-o-v-e-r-_-f-i-l-e-s-_-g-l-o-b-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -f-i-l-e- -d-i-s-c-o-v-e-r-y- -w-i-t-h- -g-l-o-b- -p-a-t-t-e-r-n-s-.-"-"-"-
- - - - - - - - -r-o-o-t- -=- -P-a-t-h-(-_-_-f-i-l-e-_-_-)-.-p-a-r-e-n-t-.-p-a-r-e-n-t-.-p-a-r-e-n-t-
- - - - - - - - -p-a-t-t-e-r-n-s- -=- -[-"-t-e-s-t-s-/-*-*-/-*-.-p-y-"-]-
-
- - - - - - - - -f-i-l-e-s- -=- -d-i-s-c-o-v-e-r-_-f-i-l-e-s-(-r-o-o-t-,- -p-a-t-t-e-r-n-s-)-
-
- - - - - - - - -#- -S-h-o-u-l-d- -f-i-n-d- -t-h-i-s- -t-e-s-t- -f-i-l-e-
- - - - - - - - -a-s-s-e-r-t- -l-e-n-(-f-i-l-e-s-)- ->- -0-
- - - - - - - - -a-s-s-e-r-t- -a-l-l-(-f-.-s-u-f-f-i-x- -=-=- -"-.-p-y-"- -f-o-r- -f- -i-n- -f-i-l-e-s-)-
-
-
-c-l-a-s-s- -T-e-s-t-V-e-r-i-f-i-e-r-A-g-e-n-t-:-
- - - - -"-"-"-T-e-s-t- -v-e-r-i-f-i-e-r- -a-g-e-n-t- -f-u-n-c-t-i-o-n-a-l-i-t-y-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-v-e-r-i-f-i-e-r-_-i-n-i-t-i-a-l-i-z-a-t-i-o-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -v-e-r-i-f-i-e-r- -a-g-e-n-t- -i-n-i-t-i-a-l-i-z-a-t-i-o-n-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -V-e-r-i-f-i-e-r-A-g-e-n-t-(-)-
- - - - - - - - -a-s-s-e-r-t- -a-g-e-n-t-.-n-a-m-e- -=-=- -"-v-e-r-i-f-y-"-
-
- - - - -d-e-f- -t-e-s-t-_-v-e-r-i-f-i-e-r-_-r-u-n-_-o-n-_-t-e-m-p-_-d-i-r-e-c-t-o-r-y-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -v-e-r-i-f-i-e-r- -r-u-n-s- -w-i-t-h-o-u-t- -c-r-a-s-h-i-n-g-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -V-e-r-i-f-i-e-r-A-g-e-n-t-(-)-
-
- - - - - - - - -w-i-t-h- -t-e-m-p-f-i-l-e-.-T-e-m-p-o-r-a-r-y-D-i-r-e-c-t-o-r-y-(-)- -a-s- -t-m-p-d-i-r-:-
- - - - - - - - - - - - -t-m-p-p-a-t-h- -=- -P-a-t-h-(-t-m-p-d-i-r-)-
-
- - - - - - - - - - - - -#- -C-r-e-a-t-e- -a- -s-i-m-p-l-e- -m-a-r-k-d-o-w-n- -f-i-l-e-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e- -=- -t-m-p-p-a-t-h- -/- -"-t-e-s-t-.-m-d-"-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e-.-w-r-i-t-e-_-t-e-x-t-(-"-#- -T-e-s-t-\-n-[-L-i-n-k-]-(-f-i-l-e-.-m-d-)-"-)-
-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-t-m-p-p-a-t-h-)-
-
- - - - - - - - - - - - -a-s-s-e-r-t- -i-s-i-n-s-t-a-n-c-e-(-r-e-s-u-l-t-,- -A-g-e-n-t-R-e-s-u-l-t-)-
- - - - - - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-n-a-m-e- -=-=- -"-v-e-r-i-f-y-"-
-
- - - - -@-p-y-t-e-s-t-.-m-a-r-k-.-s-k-i-p-(-r-e-a-s-o-n-=-"-V-e-r-i-f-i-e-r- -a-g-e-n-t- -u-s-e-s- -s-p-e-c-i-f-i-c- -p-a-t-t-e-r-n-s- -f-o-r- -f-i-l-e- -d-i-s-c-o-v-e-r-y-.- -T-e-s-t- -n-e-e-d-s- -a-d-j-u-s-t-m-e-n-t- -f-o-r- -p-r-o-p-e-r- -p-a-t-t-e-r-n- -m-a-t-c-h-i-n-g-.-"-)-
- - - - -d-e-f- -t-e-s-t-_-v-e-r-i-f-i-e-r-_-d-e-t-e-c-t-s-_-m-i-s-s-i-n-g-_-l-o-c-a-l-_-f-i-l-e-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -v-e-r-i-f-i-e-r- -d-e-t-e-c-t-s- -m-i-s-s-i-n-g- -l-o-c-a-l- -f-i-l-e-s-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -V-e-r-i-f-i-e-r-A-g-e-n-t-(-)-
-
- - - - - - - - -w-i-t-h- -t-e-m-p-f-i-l-e-.-T-e-m-p-o-r-a-r-y-D-i-r-e-c-t-o-r-y-(-)- -a-s- -t-m-p-d-i-r-:-
- - - - - - - - - - - - -t-m-p-p-a-t-h- -=- -P-a-t-h-(-t-m-p-d-i-r-)-
-
- - - - - - - - - - - - -#- -C-r-e-a-t-e- -m-a-r-k-d-o-w-n- -w-i-t-h- -b-r-o-k-e-n- -l-o-c-a-l- -l-i-n-k-
- - - - - - - - - - - - -#- -N-o-t-e-:- -A-g-e-n-t- -u-s-e-s- -d-i-s-c-o-v-e-r-_-f-i-l-e-s-(-)- -w-i-t-h- -s-p-e-c-i-f-i-c- -p-a-t-t-e-r-n-s-
- - - - - - - - - - - - -#- -T-h-i-s- -t-e-s-t- -n-e-e-d-s- -t-o- -m-a-t-c-h- -t-h-e- -e-x-p-e-c-t-e-d- -f-i-l-e- -s-t-r-u-c-t-u-r-e-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e- -=- -t-m-p-p-a-t-h- -/- -"-t-e-s-t-.-m-d-"-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e-.-w-r-i-t-e-_-t-e-x-t-(-"-[-B-r-o-k-e-n-]-(-m-i-s-s-i-n-g-_-f-i-l-e-.-m-d-)-"-)-
-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-t-m-p-p-a-t-h-)-
-
- - - - - - - - - - - - -#- -S-h-o-u-l-d- -d-e-t-e-c-t- -t-h-e- -m-i-s-s-i-n-g- -f-i-l-e-
- - - - - - - - - - - - -a-s-s-e-r-t- -l-e-n-(-r-e-s-u-l-t-.-i-s-s-u-e-s-)- ->- -0-
- - - - - - - - - - - - -a-s-s-e-r-t- -a-n-y-(-i-s-s-u-e-.-g-e-t-(-"-e-r-r-o-r-"-)- -=-=- -"-m-i-s-s-i-n-g-_-l-o-c-a-l-_-p-a-t-h-"- -f-o-r- -i-s-s-u-e- -i-n- -r-e-s-u-l-t-.-i-s-s-u-e-s-)-
-
- - - - -d-e-f- -t-e-s-t-_-v-e-r-i-f-i-e-r-_-i-g-n-o-r-e-s-_-m-a-i-l-t-o-_-l-i-n-k-s-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -v-e-r-i-f-i-e-r- -i-g-n-o-r-e-s- -m-a-i-l-t-o- -l-i-n-k-s-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -V-e-r-i-f-i-e-r-A-g-e-n-t-(-)-
-
- - - - - - - - -w-i-t-h- -t-e-m-p-f-i-l-e-.-T-e-m-p-o-r-a-r-y-D-i-r-e-c-t-o-r-y-(-)- -a-s- -t-m-p-d-i-r-:-
- - - - - - - - - - - - -t-m-p-p-a-t-h- -=- -P-a-t-h-(-t-m-p-d-i-r-)-
-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e- -=- -t-m-p-p-a-t-h- -/- -"-t-e-s-t-.-m-d-"-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e-.-w-r-i-t-e-_-t-e-x-t-(-"-[-E-m-a-i-l-]-(-m-a-i-l-t-o-:-t-e-s-t-@-e-x-a-m-p-l-e-.-c-o-m-)-"-)-
-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-t-m-p-p-a-t-h-)-
-
- - - - - - - - - - - - -#- -S-h-o-u-l-d- -n-o-t- -f-l-a-g- -m-a-i-l-t-o- -l-i-n-k-s- -a-s- -i-s-s-u-e-s-
- - - - - - - - - - - - -m-a-i-l-t-o-_-i-s-s-u-e-s- -=- -[-i- -f-o-r- -i- -i-n- -r-e-s-u-l-t-.-i-s-s-u-e-s- -i-f- -"-m-a-i-l-t-o-"- -i-n- -s-t-r-(-i-.-g-e-t-(-"-l-i-n-k-"-,- -"-"-)-)-]-
- - - - - - - - - - - - -a-s-s-e-r-t- -l-e-n-(-m-a-i-l-t-o-_-i-s-s-u-e-s-)- -=-=- -0-
-
-
-c-l-a-s-s- -T-e-s-t-D-o-c-s-I-n-t-e-g-r-i-t-y-A-g-e-n-t-:-
- - - - -"-"-"-T-e-s-t- -d-o-c-s- -i-n-t-e-g-r-i-t-y- -a-g-e-n-t-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-d-o-c-s-_-i-n-t-e-g-r-i-t-y-_-i-n-i-t-i-a-l-i-z-a-t-i-o-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -d-o-c-s- -i-n-t-e-g-r-i-t-y- -a-g-e-n-t- -i-n-i-t-i-a-l-i-z-a-t-i-o-n-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -D-o-c-s-I-n-t-e-g-r-i-t-y-A-g-e-n-t-(-)-
- - - - - - - - -a-s-s-e-r-t- -a-g-e-n-t-.-n-a-m-e- -=-=- -"-d-o-c-s-"-
-
- - - - -d-e-f- -t-e-s-t-_-d-o-c-s-_-i-n-t-e-g-r-i-t-y-_-r-u-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -d-o-c-s- -i-n-t-e-g-r-i-t-y- -a-g-e-n-t- -r-u-n-s-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -D-o-c-s-I-n-t-e-g-r-i-t-y-A-g-e-n-t-(-)-
-
- - - - - - - - -w-i-t-h- -t-e-m-p-f-i-l-e-.-T-e-m-p-o-r-a-r-y-D-i-r-e-c-t-o-r-y-(-)- -a-s- -t-m-p-d-i-r-:-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-P-a-t-h-(-t-m-p-d-i-r-)-)-
-
- - - - - - - - - - - - -a-s-s-e-r-t- -i-s-i-n-s-t-a-n-c-e-(-r-e-s-u-l-t-,- -A-g-e-n-t-R-e-s-u-l-t-)-
- - - - - - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-n-a-m-e- -=-=- -"-d-o-c-s-"-
-
-
-c-l-a-s-s- -T-e-s-t-U-n-i-c-o-d-e-S-a-n-i-t-i-z-e-r-A-g-e-n-t-:-
- - - - -"-"-"-T-e-s-t- -u-n-i-c-o-d-e- -s-a-n-i-t-i-z-e-r- -a-g-e-n-t-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-u-n-i-c-o-d-e-_-s-a-n-i-t-i-z-e-r-_-i-n-i-t-i-a-l-i-z-a-t-i-o-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -u-n-i-c-o-d-e- -s-a-n-i-t-i-z-e-r- -i-n-i-t-i-a-l-i-z-a-t-i-o-n-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -U-n-i-c-o-d-e-S-a-n-i-t-i-z-e-r-A-g-e-n-t-(-)-
- - - - - - - - -a-s-s-e-r-t- -a-g-e-n-t-.-n-a-m-e- -=-=- -"-u-n-i-c-o-d-e-"-
-
- - - - -d-e-f- -t-e-s-t-_-u-n-i-c-o-d-e-_-s-a-n-i-t-i-z-e-r-_-r-u-n-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -u-n-i-c-o-d-e- -s-a-n-i-t-i-z-e-r- -r-u-n-s-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -U-n-i-c-o-d-e-S-a-n-i-t-i-z-e-r-A-g-e-n-t-(-)-
-
- - - - - - - - -w-i-t-h- -t-e-m-p-f-i-l-e-.-T-e-m-p-o-r-a-r-y-D-i-r-e-c-t-o-r-y-(-)- -a-s- -t-m-p-d-i-r-:-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-P-a-t-h-(-t-m-p-d-i-r-)-)-
-
- - - - - - - - - - - - -a-s-s-e-r-t- -i-s-i-n-s-t-a-n-c-e-(-r-e-s-u-l-t-,- -A-g-e-n-t-R-e-s-u-l-t-)-
- - - - - - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-n-a-m-e- -=-=- -"-u-n-i-c-o-d-e-"-
-
- - - - -d-e-f- -t-e-s-t-_-u-n-i-c-o-d-e-_-s-a-n-i-t-i-z-e-r-_-d-e-t-e-c-t-s-_-s-p-e-c-i-a-l-_-c-h-a-r-s-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -u-n-i-c-o-d-e- -s-a-n-i-t-i-z-e-r- -d-e-t-e-c-t-s- -s-p-e-c-i-a-l- -c-h-a-r-a-c-t-e-r-s-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -U-n-i-c-o-d-e-S-a-n-i-t-i-z-e-r-A-g-e-n-t-(-)-
-
- - - - - - - - -w-i-t-h- -t-e-m-p-f-i-l-e-.-T-e-m-p-o-r-a-r-y-D-i-r-e-c-t-o-r-y-(-)- -a-s- -t-m-p-d-i-r-:-
- - - - - - - - - - - - -t-m-p-p-a-t-h- -=- -P-a-t-h-(-t-m-p-d-i-r-)-
-
- - - - - - - - - - - - -#- -C-r-e-a-t-e- -f-i-l-e- -w-i-t-h- -u-n-i-c-o-d-e- -c-h-a-r-a-c-t-e-r-s-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e- -=- -t-m-p-p-a-t-h- -/- -"-t-e-s-t-.-p-y-"-
- - - - - - - - - - - - -t-e-s-t-_-f-i-l-e-.-w-r-i-t-e-_-t-e-x-t-(-"-#- -T-e-s-t- -w-i-t-h- -é-m-o-j-i- -🎉-"-)-
-
- - - - - - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-t-m-p-p-a-t-h-)-
-
- - - - - - - - - - - - -#- -M-a-y- -o-r- -m-a-y- -n-o-t- -f-l-a-g- -d-e-p-e-n-d-i-n-g- -o-n- -i-m-p-l-e-m-e-n-t-a-t-i-o-n-
- - - - - - - - - - - - -#- -J-u-s-t- -c-h-e-c-k- -i-t- -d-o-e-s-n-'-t- -c-r-a-s-h-
- - - - - - - - - - - - -a-s-s-e-r-t- -i-s-i-n-s-t-a-n-c-e-(-r-e-s-u-l-t-,- -A-g-e-n-t-R-e-s-u-l-t-)-
-
-
-c-l-a-s-s- -T-e-s-t-A-g-e-n-t-I-n-t-e-g-r-a-t-i-o-n-:-
- - - - -"-"-"-T-e-s-t- -a-g-e-n-t-s- -o-n- -a-c-t-u-a-l- -p-r-o-j-e-c-t-.-"-"-"-
-
- - - - -d-e-f- -t-e-s-t-_-r-u-n-_-v-e-r-i-f-i-e-r-_-o-n-_-p-r-o-j-e-c-t-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -v-e-r-i-f-i-e-r- -o-n- -a-c-t-u-a-l- -G-I-F-T- -p-r-o-j-e-c-t-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -V-e-r-i-f-i-e-r-A-g-e-n-t-(-)-
- - - - - - - - -p-r-o-j-e-c-t-_-r-o-o-t- -=- -P-a-t-h-(-_-_-f-i-l-e-_-_-)-.-p-a-r-e-n-t-.-p-a-r-e-n-t-.-p-a-r-e-n-t-
-
- - - - - - - - -#- -J-u-s-t- -v-e-r-i-f-y- -i-t- -d-o-e-s-n-'-t- -c-r-a-s-h-
- - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-p-r-o-j-e-c-t-_-r-o-o-t-)-
-
- - - - - - - - -a-s-s-e-r-t- -i-s-i-n-s-t-a-n-c-e-(-r-e-s-u-l-t-,- -A-g-e-n-t-R-e-s-u-l-t-)-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-n-a-m-e- -=-=- -"-v-e-r-i-f-y-"-
-
- - - - -d-e-f- -t-e-s-t-_-r-u-n-_-d-o-c-s-_-i-n-t-e-g-r-i-t-y-_-o-n-_-p-r-o-j-e-c-t-(-s-e-l-f-)-:-
- - - - - - - - -"-"-"-T-e-s-t- -d-o-c-s- -i-n-t-e-g-r-i-t-y- -o-n- -a-c-t-u-a-l- -G-I-F-T- -p-r-o-j-e-c-t-.-"-"-"-
- - - - - - - - -a-g-e-n-t- -=- -D-o-c-s-I-n-t-e-g-r-i-t-y-A-g-e-n-t-(-)-
- - - - - - - - -p-r-o-j-e-c-t-_-r-o-o-t- -=- -P-a-t-h-(-_-_-f-i-l-e-_-_-)-.-p-a-r-e-n-t-.-p-a-r-e-n-t-.-p-a-r-e-n-t-
-
- - - - - - - - -r-e-s-u-l-t- -=- -a-g-e-n-t-.-r-u-n-(-p-r-o-j-e-c-t-_-r-o-o-t-)-
-
- - - - - - - - -a-s-s-e-r-t- -i-s-i-n-s-t-a-n-c-e-(-r-e-s-u-l-t-,- -A-g-e-n-t-R-e-s-u-l-t-)-
- - - - - - - - -a-s-s-e-r-t- -r-e-s-u-l-t-.-n-a-m-e- -=-=- -"-d-o-c-s-"-
-