name: GIFT Framework - Notebook Autonome

on:
  push:
    branches: [ main, master ]
    paths:
      - 'GIFT_Autonomous_Notebook.ipynb'
      - 'requirements.txt'
  pull_request:
    branches: [ main, master ]
  schedule:
    # Exécution quotidienne à 6h UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert jupyter
        
    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute GIFT_Autonomous_Notebook.ipynb --output GIFT_Autonomous_Notebook_Executed.ipynb
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: gift-notebook-results
        path: |
          GIFT_Autonomous_Notebook_Executed.ipynb
          GIFT_Autonomous_Results_*.csv
          GIFT_Autonomous_Results_*.json
          
    - name: Create summary
      run: |
        echo "# GIFT Framework - Résultats d'Exécution" > execution_summary.md
        echo "" >> execution_summary.md
        echo "**Date d'exécution:** $(date)" >> execution_summary.md
        echo "**Statut:** ✅ Succès" >> execution_summary.md
        echo "" >> execution_summary.md
        echo "## Fichiers générés:" >> execution_summary.md
        ls -la GIFT_Autonomous_Results_* >> execution_summary.md || echo "Aucun fichier de résultats trouvé"
        
    - name: Upload summary
      uses: actions/upload-artifact@v3
      with:
        name: execution-summary
        path: execution_summary.md
