name: Scientific Notebook Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/gift_support_notebook.ipynb'
      - 'requirements.txt'
      - 'environment.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/gift_support_notebook.ipynb'
      - 'requirements.txt'
      - 'environment.yml'
  schedule:
    # Validation hebdomadaire le dimanche à 8h UTC
    - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  validate-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbconvert jupyter
        
    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute docs/gift_support_notebook.ipynb --output-dir=./validation_output/
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: notebook-validation-results
        path: validation_output/
        retention-days: 7
        
    - name: Create validation summary
      if: always()
      run: |
        echo "# Notebook Validation Summary" > validation_summary.md
        echo "" >> validation_summary.md
        echo "**Date:** $(date)" >> validation_summary.md
        echo "**Status:** ${{ job.status }}" >> validation_summary.md
        echo "" >> validation_summary.md
        echo "## Files processed:" >> validation_summary.md
        ls -la validation_output/ >> validation_summary.md || echo "No output files generated"
        
    - name: Upload summary
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validation-summary
        path: validation_summary.md
        retention-days: 7
